version: "3.7"

services:
  backend:
    build: 
      context: ./backend
    ports: 
      - 5000:5000
    environment:
      MONGO_URL: mongodb+srv://ray:ray890110@cluster0.jp3nt.mongodb.net/Final?retryWrites=true&w=majority
      PORT: 5000
  frontend:
    build: 
      context: ./frontend
    ports: 
      - 3000:3000
    environment:
      REACT_APP_SERVER_URL: http://localhost:5000