apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: onlinetemple-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 443
  loadBalancerIP: "35.194.206.199"